version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: wearables
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wearables_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
